import { Metadata } from "next";
import { Footer } from "../components/layout/Footer";
import { Header } from "../components/layout/Header";
import "./globals.css";

import { createMetadata } from "lib/metadata";

export const metadata: Metadata = createMetadata({
  title: "Silver Coin: Age of Monster Hunters – Official Board Game Website",
  description: "Silver Coin: Age of Monster Hunters is a competitive adventure eurogame set in the dark fantasy world of Atosia...",
  url: "/",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={"bg-background"}>
        <Header />
        <main className={'min-h-screen bg-[url("/images/bg_texture.webp")] text-white pt-20 text-2xl'}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
