"use client"
import { Footer } from "../components/layout/Footer"
import { Header } from "../components/layout/Header"
import "./globals.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={"bg-background"}>
        <Header />
        <main className={'min-h-screen pb-28 bg-[url("/images/bg_texture.webp")] text-white pt-20 text-2xl'}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
