import Head from 'next/head'

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p className="bg-red-200 text-2xl">hello world</p>
      </main>
    </div>
  )
}
